### ISSUE TITLE
wrong example of `hgd_plot`

### ISSUE THREAD

**Issue by eitsupi** [nx10/httpgd#103]
### Describe the bug

It seems that we are seeing examples of `hgd_svg` instead of `hgd_plot`.

https://github.com/nx10/httpgd/blob/da3fa0049aaf650b96909d4df1fe514cad72c277/R/httpgd.R#L349-L366

**Comment by nx10** [comment]
Thanks! e8d7aec45759128ec0f5416de81469d5b1e25cc0
