### ISSUE TITLE
Add explanation on how to render httpgd plots below an rmarkdown chunk

### ISSUE THREAD

**Issue by franfram** [nx10/httpgd#104]
Hello, 
amazing package. 

I just saw Kun Ren's talk on youtube: 
https://www.youtube.com/watch?v=9xXBDU2z_8Y

But I can't find a way to render httpgd plots inside an rmarkdown chunk like Kun did in the talk

![Screenshot from 2022-03-23 17-03-17](https://user-images.githubusercontent.com/18502770/159793597-9f232eff-6b17-41bf-ab85-aca7c97f46da.png)

Maybe add a description on how to do this?

Cheers!

**Comment by renkun-ken** [comment]
The httpgd plots are actually not inside or below a rmarkdown chunk in the same editor, it is actually in separate tabs in another editor group.

Install httpgd, enable `r.plot.useHttpgd` in vscode settings, and the httpgd plot viewer will show up when you plot.

**Comment by nx10** [comment]
Thank you for your interest, and Kun Ren for responding!

I am currently working on refactoring and modularizing large parts of this package and will try to improve the documentation when I am done.
