### ISSUE TITLE
server is closed immediately

### ISSUE THREAD

**Issue by hodanli** [nx10/httpgd#107]
when i run `hgd()` the server is closed immediately. below is printed in the terminal.

```
httpgd server running at:
  http://127.0.0.1:61320/live?token=uiV2Ebdr
Server closing... Closed.
```

### Screenshots

![image](https://user-images.githubusercontent.com/6535865/161536232-1fc40020-bdc1-42e2-afc1-591dac4f0be2.png)

### Environment
 - OS: windows
 - R version: 4.1.3

**Comment by eitsupi** [comment]
I do not think this is a function that can be used within RStudio's RMarkdown cell.
Try running it in the R console.

**Comment by hodanli** [comment]
thanks. this solved the issue.
