### ISSUE TITLE
return Error: getrandom from vscode terminal

### ISSUE THREAD

**Issue by ZhengJIN94** [nx10/httpgd#112]
I followed the tutorial to install httpgd package.

And when I draw figures with vscode, it returns **"Error: getrandom"**

However, if I disable r.plot.httpgd, it can draw figures successfully. 

Is there any way to solve the problem ?

**Comment by nx10** [comment]
Thanks for opening the issue. From the error message it seems like this is a VScode problem, maybe @ManuelHentschel @renkun-ken can help.

**Comment by nx10** [comment]
Do you still encounter this issue?
