### ISSUE TITLE
Could not find the function .vsc.browser

### ISSUE THREAD

**Issue by barbosawf** [nx10/httpgd#117]
### Describe the bug
Could not find the function .vsc.browser

![image](https://user-images.githubusercontent.com/105462541/180093157-f5e5f5de-5421-4622-b07e-845fb25ad760.png)

### Environment
 - OS: Windows
 - Browser:  brave (default), microsoft edge, chrome, firefox
 - R version: 4.1.1
 - httpgd version: I installed using remotes::install_github("nx10/httpgd") in 20-july-2022

### R.profile
_Firstly, I use the following code to give access to Rprofile_
```
usethis::edit_r_profile()
```

_then, in Rprofile I wrote the following code:_
```
if (interactive() && Sys.getenv("TERM_PROGRAM") == "vscode") {
  if ("httpgd" %in% .packages(all.available = TRUE)) {
    options(vsc.plot = FALSE)
    options(device = function(...) {
      httpgd::hgd(silent = TRUE)
      .vsc.browser(httpgd::hgd_url(), viewer = "Beside")
    })
  }
}
```

**Comment by eitsupi** [comment]
I don't think this is a httpgd problem.
Where did your Rprofile code come from?
The `.vsc.browser` function does not seem included in vscode-R.
https://github.com/REditorSupport/vscode-R/blob/c76d3dfe81d265ccbde9d8314cc39f6601e1d758/R/session/vsc.R

**Comment by barbosawf** [comment]
Hello! It comes from here: https://renkun.me/2020/06/16/using-httpgd-in-vscode-a-web-based-svg-graphics-device/

**Comment by eitsupi** [comment]
Sorry, `.vsc.browser` exist here. https://github.com/REditorSupport/vscode-R/blob/3e483c311798e2136ee36bb18ef0f9374d281e60/R/session/init.R#L64

Anyway, this is not a httpgd issue but a vscode-R configuration, so I suggest you close this issue and ask your question in the vscode-R repository.

**Comment by barbosawf** [comment]
Ok! Thanks!

**Comment by jiangfenglyu** [comment]
hope this issue link could give you some help.
https://github.com/REditorSupport/vscode-R/issues/1094

best regards
