### ISSUE TITLE
Broken image in this package (pkgdown) home page

### ISSUE THREAD

**Issue by espinielli** [nx10/httpgd#127]
### Describe the bug
The (pkgdown) home page of this package shows a broken image

### To Reproduce
Visit the website for this package 

### Expected behavior
The image should not be broken 

### Environment
 - OS: Android 
 - Browser: Brave
 - R version: NA
 - httpgd version: NA

**Comment by nx10** [comment]
Which image is broken?
Could you attach a screenshot or link?

Thanks!

**Comment by espinielli** [comment]
I was on my mobile and the animated image was not showing up and displayed as a broken image icon... I could not easily grab a snapshot at the time of the issue report.
I tried again now on both the desktop and mobile and the image is there, so I think it was a bandwidth problem...
Sorry for the fuss

**Comment by nx10** [comment]
Thanks anyways! I also had some random GitHub server issues over the last couple days so maybe you were just unlucky and opened the page exactly as GitHub was doing maintenance on something.
