### ISSUE TITLE
Package installation currently fails for v1.3.0

### ISSUE THREAD

**Issue by benz0li** [nx10/httpgd#128]
### Describe the bug

Package installation currently fails for v1.3.0: [httpgd-1.3.0_install-log.txt](https://github.com/nx10/httpgd/files/10480667/httpgd-1.3.0_install-log.txt)

### To Reproduce

1.  Shell:
    ```bash
    docker run --rm -ti registry.gitlab.b-data.ch/r/ver:4.2.2 bash
    ```
1.  Shell (in container): 
    ```bash
    apt-get update \
      && apt-get -y install --no-install-recommends \
        libcairo2-dev \
        libfontconfig1-dev \
        libxml2-dev
    ```
1.  Shell (in container): 
    ```bash
    install2.r --error --deps TRUE --skipinstalled httpgd
    ```

### Expected behavior

Installation succeeding.

### Screenshots

none

### Environment
 - OS: GNU/Linux 11 (bullseye)
 - Browser: irrelevant
 - R version: 4.2.2
 - httpgd version: 1.3.0

### Additional context

```R
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 11 (bullseye)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.13.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2
```

**Comment by nx10** [comment]
That's unfortunate I provided a patch weeks ago which was rejected due to false positives in BH ( https://github.com/eddelbuettel/bh/issues/88 ) 
I will re-upload momentarily.

Sorry for the inconveniences everybody I moved to the US from Europe last week and still have somewhat limited internet access.

**Comment by benz0li** [comment]
> I will re-upload momentarily.

Thank you.

> Sorry for the inconveniences everybody

No worries.

**Comment by benz0li** [comment]
Archived once again?!? https://cran.r-project.org/incoming/archive/

**Comment by nx10** [comment]
Yes, I just got these comments

```
Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      hgd_test_pattern.Rd:  \value

\dontrun{} should only be used if the example really cannot be executed
(e.g. because of missing additional software, missing API keys, ...) by
the user. That's why wrapping examples in \dontrun{} adds the comment
("# Not run:") as a warning for the user.
Does not seem necessary.
Please unwrap the examples if they are executable in < 5 sec, or replace
\dontrun{} with \donttest{}.

Please ensure that your functions do not write by default or in your
examples/vignettes/tests in the user's home filespace (including the
package directory and getwd()). This is not allowed by CRAN policies.
Please omit any default path in writing functions. In your
examples/vignettes/tests you can write to tempdir().


Please always make sure to reset to user's options(), working directory
or par() after you changed it in examples and vignettes and demos.
e.g.:
oldpar <- par(mfrow = c(1,2))
...
par(oldpar)

Please fix and resubmit.
```

I am not sure this is entirely accurate (and it was fine on CRAN for the last 2 years), but will take time time to make all the changes they want.

**Comment by eitsupi** [comment]
I think I can help with roxygen comments and test modifications.

**Comment by nx10** [comment]
@eitsupi Any help is very appreciated! Just make sure to work on the branch I linked.

I will also be able to work on httpgd again soon.

**Comment by benz0li** [comment]
I am installing httpgd 1.3.0 from archive and staying with BH 1.78.0-0 until this issue is resolved.

**Comment by eitsupi** [comment]
I did fix roxygen comments on #129.
However, I could not figure out where the problem of writing temporary files was.

**Comment by nx10** [comment]
> I could not figure out where the problem of writing temporary files was.

This is what I was hinting at with "I am not sure [the CRAN review] is entirely accurate". I do not think httpgd ever writes files as a side effect.

**Comment by nx10** [comment]
Thanks @eitsupi for the help! I will prepare everthing and resubmit later today.

**Comment by nx10** [comment]
We are up again. CRAN usually takes 1-3 days to build windows and Mac binaries: https://CRAN.R-project.org/package=httpgd

**Comment by nx10** [comment]
Yes R universe and anaconda are definitely planned but I have kept pushing them off for the 2.0 release. There is not much left for that and it will change all of the build logic.
