### ISSUE TITLE
Deleting the wrong plot

### ISSUE THREAD

**Issue by renkun-ken** [nx10/httpgd#13]
Hitting delete could delete the wrong plot. For example, run the following code:

```r
httpgd::httpgd()
utils::browseURL(httpgd::httpgdURL())
for (i in 1:10) {
  plot(rnorm(100), main = sprintf("plot %d", i))
  abline(h = 0, col = "red")
  points(rnorm(100), col = "blue")
}
```

Ten plots are created. Now it is showing plot 10.

Press right and navigate to plot 1 and hit delete. Then it shows plot 10. Now press right again. It is showing plot 1 again, which is supposed to be deleted. Now press right, it shows plot 3. Now it looks like plot 2 is removed instead of plot 1.

**Comment by nx10** [comment]
This should be fixed now. The browser was caching requests from before the removal.

**Comment by renkun-ken** [comment]
Thanks for the fix!

However, removing the last image seems problematic too.

![Kapture 2020-06-06 at 22 58 32](https://user-images.githubusercontent.com/4662568/83947407-49a74780-a849-11ea-84ba-6e28a3080203.gif)

**Comment by nx10** [comment]
Should be fixed now

**Comment by renkun-ken** [comment]
The latest commit works quite nicely now. Thanks!
