### ISSUE TITLE
No plot viewer shown in vscode

### ISSUE THREAD

**Issue by EngineeringScholar** [nx10/httpgd#131]
httpgd package was installed, and r.plot.useHttpgd is set to true. However running a simple plot command, plot(rnorm(100)) as an example, only outputs a Rplots.pdf file. I was expecting a plot viewer panel in the vscode, like in Rstudio. Is this a bug or I missed something?
I have R4.2.2 installed and Radian, languageserver, vscDebugger all installed, along with R extension and R Debugger extension. Googling all day long, but no solution found on this. Thanks.

**Comment by renkun-ken** [comment]
If you call explicitly `httpgd::hgd()` and it works properly, then it should probably be an issue in vscode. See https://github.com/REditorSupport/vscode-R/issues/1297.

**Comment by nx10** [comment]
Seems to be resolved over at vscode-R.
Thanks @renkun-ken !

**Comment by HUGOSAMA1121** [comment]
> Seems to be resolved over at vscode-R.似乎已在 vscode-R 解决。 Thanks @renkun-ken ! 谢谢 ！

Please tell me how to solve it. I also encountered the same problem and my httpgd can return the url correctly.
![image](https://github.com/user-attachments/assets/81e66e34-bb1c-47cf-8b99-2708f51a53f1)
