### ISSUE TITLE
Can't clear previous plots when re-running a new R script

### ISSUE THREAD

**Issue by DrAnnaSchwartz** [nx10/httpgd#132]
Unless I close the terminal and open a new r terminal, all previous plots are shown in the plot viewer, like the one below:

![image](https://user-images.githubusercontent.com/121742301/217358591-f8086bb9-c2c2-4fc5-8ec6-b37b565d7f84.png)

Is there a way to clear the previous plots when running a new r script? 

Another question - Rplots.pdf is generated everytime I ran a R script containing plot functions. How can I suppress the pdf output? 

Thanks for your help!

**Comment by PMKmw** [comment]
Are you using Httpgd ??

**Comment by nx10** [comment]
Thank you for reaching out, but this seems to be an [issue for the VSCode R integration](https://github.com/REditorSupport/vscode-R/issues) and not specific to `httpgd` - Clearing the plot history is be something that vscode-r would need to take care of (as `httpgd` does not know anything about which script is open at what time). Also Rplots.pdf is not produced by `httpgd`.
