### ISSUE TITLE
http no response when get plot

### ISSUE THREAD

**Issue by lmdu** [nx10/httpgd#142]
Hi, and thank you for this greate pacakge!

I used rchitect and httpgd to interact with R and view plot. The httpgd server started ok. However, only the first thumbnail of plot can display, the maximized plot can not display. I am not sure the problem is httpgd or rchitect. Can you help me to solve this problem. Thanks!

### To Reproduce

```python
import time
import rchitect

rchitect.init()
rchitect.rcall('library', 'reticulate')
rchitect.rcall('library', 'httpgd')
rchitect.rcall('hgd')
rchitect.rcall('hgd_browse')

rchitect.reval('x<-c(1,2,3,4,5,6); y<-c(4,5,6,7,8,9); plot(x,y)')

time.sleep(10)
```

### Environment
 - OS: Windows 11
 - Browser: Edge 120.0.2210.77
 - R version: 4.3.2
 - httpgd version: 1.3.1 and 2.0.0.9000

**Comment by genmeblog** [comment]
@lmdu can you elaborate a little bit how did you resolve this issue? I'm experienceing the same with the different setup.

**Comment by lmdu** [comment]
I have not resolved the issue. I used httpgd api in R instead of http to get svg plot.
