### ISSUE TITLE
Use GH releases for CRAN releases

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [nx10/httpgd#158]
### Is your proposal related to a problem?

Many CRAN R packages which are hosted on GH have GH releases matching their CRAN release versions.

This aids in
- restoring historic versions, 
- installing the current release (in case it has been dropped from CRAN temporarily) and
- examining the development process by third-party developers.

### Describe the solution you'd like

Future releases to CRAN should be tagged in this repo using the GH releases facility.

### Describe alternatives you've considered

- CRAN mirror repo <https://github.com/cran/httpgd>
- CRAN archive <https://cran.r-project.org/src/contrib/Archive/httpgd/>
- Posit package manager <https://packagemanager.posit.co/client/#/repos/cran/packages/overview?search=httpgd>
- R universe <https://nx10.r-universe.dev/httpgd>
- Amending README

### Additional context

Extra perk: you should get ❤️  👍  👀 🎉  🚀  reactions from GH users on every release 😉

**Comment by nx10** [comment]
Thank you, I fully agree and have started to make GitHub releases for both `unigd` and `httpgd`.
