### ISSUE TITLE
Connect remotely (bind to 0.0.0.0)

### ISSUE THREAD

**Issue by jeroen** [nx10/httpgd#21]
I would like to SSH into my remote machine, and see plots locally in my browser. However if I bind to the default `127.0.0.1` then we cannot connect from outside.

So instead on the remote machine, I start with:

```r
httpgd::httpgd('0.0.0.0')
# httpgd live server running at:
#   http://0.0.0.0:33095/live?token=WNoy3Nsn
```

My local browser can connect to the remote http server (if I replace `0.0.0.0` with my hostname) however the html/js client page doesn't work because javascript is trying to connect to `0.0.0.0`.

<img width="685" alt="Screen Shot 2020-06-23 at 12 11 07 AM" src="https://user-images.githubusercontent.com/216319/85340285-1bcb2f80-b4e6-11ea-8738-feef4141c1db.png">

I also tried starting the server with `httpgd::httpgd('actual.hostname.com')` but then I couldn't even connect to the http server remotely.

**Comment by renkun-ken** [comment]
I remember I tried this a while ago and it worked (or I don't remember correctly?). I just tried with a remote server listening `0.0.0.0` and it does not work but listening its real intranet IP works (I connect to the intranet from outside via sshuttle).

**Comment by jeroen** [comment]
Yes using the host ip address seems to work. But it would be nice if it would work with `0.0.0.0` as well.

You probably need to change the html/js client to use the same server address for polling as in `window.location` because the real intranet IP is often different when the server is behind a proxy.

**Comment by renkun-ken** [comment]
Yes, definitely.

**Comment by nx10** [comment]
Thank you for opening the issue.
I just pushed changes that should solve this (0d931080391e8d2d6153e35e9e7c73ffd02ddc36).
The live client will now access the address to which the `GET /live`  request was sent.

**Comment by jeroen** [comment]
Hmm it's not working for me. The server is just giving me 404's with "Unauthorized." and the client seems to be assuming json

<img width="674" alt="Screen Shot 2020-06-23 at 1 34 27 AM" src="https://user-images.githubusercontent.com/216319/85345089-cdbc2900-b4f1-11ea-9bee-17bca747834d.png">

**Comment by nx10** [comment]
Should work now aaf803f67bf4b47fee1b203daf4b5cc5e97fe201

**Comment by renkun-ken** [comment]
It works for me now. Thanks!
