### ISSUE TITLE
live share compatibility or other possibility for remote view of a plot?

### ISSUE THREAD

**Issue by Draic** [nx10/httpgd#26]
I am not sure if this is possible, but is there a way to expose the http server to live share participants? This way plots would be visible for other participants to see, which currently does not seem to be possible without azure

alternatively accessing the http server from outside the network does not seem to work? I have set up the server with a port that is accessable from outside the home network, but the server will refuse outside connections.

**Comment by nx10** [comment]
Remote access should work. Try using:
```R
httpgd(host="0.0.0.0")
```
And then connect to either the public IP or your host name.

I am not familiar with live share, but maybe @renkun-ken knows more about that.
If it has a HTTP based API support should be possible.

**Comment by renkun-ken** [comment]
If you are using azure (or any other cloud VM provider) to share plot, you might need to use a fixed port and set up the network rules to allow traffic from/to that port.

**Comment by nx10** [comment]
I think they are referring to this: https://visualstudio.microsoft.com/de/services/live-share/

**Comment by Draic** [comment]
setting host to 0.0.0.0 was the solution to get access from outside the network. Thanks @nx10 
This is still not ideal, as I want to have plots visible for online classrooms and having them open up a extra browser window is a hassle. But I guess this is more a limit of Live Share. Sharing the http server in Live Share seems to only work with Azure, which I do not have and even then it wouldn't let me just have a plot be visible after it's been generated... 

Thanks for the help figuring out the remote access :)
