### ISSUE TITLE
Missing axes when par(mfrow) is specified

### ISSUE THREAD

**Issue by renkun-ken** [nx10/httpgd#29]
Sometimes, the axes in a plot could be missing.

```r
par(mfrow = c(2, 2))
m <- lm(mpg ~ cyl, data = mtcars)
plot(m)

for (i in 1:8) {
  plot(rnorm(100), main = sprintf("plot %d", i))
  abline(h = rnorm(1), col = "red")
  points(rnorm(100), col = "blue")
}
```

In the last plot, the bottom-left scatter plot does not show the axes as it should.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/4662568/86154098-311f0a00-bb35-11ea-9624-3724510dccb6.png">

I could only reproduce this on macOS with both `master` and `boost-beast` branches but not on Ubuntu. Not sure if it occurs on Windows.

**Comment by nx10** [comment]
Good catch, happens in windows too. I will look into it.

**Comment by nx10** [comment]
Should be fixed `boost-beast` branch

**Comment by renkun-ken** [comment]
Thanks! It works nicely now!
