### ISSUE TITLE
missing members in global namespace

### ISSUE THREAD

**Issue by eddieimada** [nx10/httpgd#30]
I'm getting errors when try to install the package. I have all the dependecies installed. Is there a way to fix this?
 

> * installing *source* package ‘httpgd’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/later/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/systemfonts/include' -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -fPIC  -Wall -g -O2  -c DrawData.cpp -o DrawData.o
In file included from DrawData.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: no member named
      'signbit' in the global namespace
using ::signbit;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: no member named
      'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: no member named
      'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/usr/local/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
In file included from DrawData.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isinf'
      in the global namespace
using ::isinf;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnan'
      in the global namespace
using ::isnan;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:9: error: no member named
      'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:7: error: no member named
      'isgreater' in the global namespace; did you mean '::std::greater'?
using ::isgreater;
      ^~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:728:29: note: '::std::greater'
      declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from DrawData.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:7: error: no member named
      'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:757:29: note: 
      '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from DrawData.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'isless'
      in the global namespace
using ::isless;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:327:9: error: no member named
      'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:328:9: error: no member named
      'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:329:9: error: no member named
      'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:330:9: error: no member named
      'isunordered' in the global namespace
using ::isunordered;
      ~~^
DrawData.cpp:151:21: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
                if (std::abs(dc->m_lmitre - 10.0) > 1e-3)
                    ^
DrawData.cpp:151:21: note: use function 'std::abs' instead
                if (std::abs(dc->m_lmitre - 10.0) > 1e-3)
                    ^~~~~~~~
                    std::abs
DrawData.cpp:151:21: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
DrawData.cpp:294:37: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
            svg_field(buf, "width", std::abs(m_x0 - m_x1));
                                    ^
DrawData.cpp:294:37: note: use function 'std::abs' instead
            svg_field(buf, "width", std::abs(m_x0 - m_x1));
                                    ^~~~~~~~
                                    std::abs
DrawData.cpp:294:37: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
DrawData.cpp:295:38: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
            svg_field(buf, "height", std::abs(m_y0 - m_y1));
                                     ^
DrawData.cpp:295:38: note: use function 'std::abs' instead
            svg_field(buf, "height", std::abs(m_y0 - m_y1));
                                     ^~~~~~~~
                                     std::abs
DrawData.cpp:295:38: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
DrawData.cpp:461:20: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
            return std::abs(x0 - m_x0) < CLIP_EPSILON &&
                   ^
DrawData.cpp:461:20: note: use function 'std::abs' instead
            return std::abs(x0 - m_x0) < CLIP_EPSILON &&
                   ^~~~~~~~
                   std::abs
DrawData.cpp:461:20: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
DrawData.cpp:462:20: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
                   std::abs(x1 - m_x1) < CLIP_EPSILON &&
                   ^
DrawData.cpp:462:20: note: use function 'std::abs' instead
                   std::abs(x1 - m_x1) < CLIP_EPSILON &&
                   ^~~~~~~~
                   std::abs
DrawData.cpp:462:20: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
DrawData.cpp:463:20: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
                   std::abs(y0 - m_y0) < CLIP_EPSILON &&
                   ^
DrawData.cpp:463:20: note: use function 'std::abs' instead
                   std::abs(y0 - m_y0) < CLIP_EPSILON &&
                   ^~~~~~~~
                   std::abs
DrawData.cpp:463:20: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
DrawData.cpp:464:20: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
                   std::abs(y1 - m_y1) < CLIP_EPSILON;
                   ^
DrawData.cpp:464:20: note: use function 'std::abs' instead
                   std::abs(y1 - m_y1) < CLIP_EPSILON;
                   ^~~~~~~~
                   std::abs
DrawData.cpp:464:20: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
DrawData.cpp:471:62: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
            buf->append("\" width=\"").append(std::to_string(std::abs(m_x1 - m_x0)));
                                                             ^
DrawData.cpp:471:62: note: use function 'std::abs' instead
            buf->append("\" width=\"").append(std::to_string(std::abs(m_x1 - m_x0)));
                                                             ^~~~~~~~
                                                             std::abs
DrawData.cpp:471:62: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
DrawData.cpp:472:63: warning: using integer absolute value function 'abs' when argument is of floating
      point type [-Wabsolute-value]
            buf->append("\" height=\"").append(std::to_string(std::abs(m_y1 - m_y0)));
                                                              ^
DrawData.cpp:472:63: note: use function 'std::abs' instead
            buf->append("\" height=\"").append(std::to_string(std::abs(m_y1 - m_y0)));
                                                              ^~~~~~~~
                                                              std::abs
DrawData.cpp:472:63: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
In file included from DrawData.cpp:11:
./DrawData.h:66:37: warning: private field 'm_hadj' is not used [-Wunused-private-field]
            double m_x, m_y, m_rot, m_hadj;
                                    ^
10 warnings and 13 errors generated.
make: *** [DrawData.o] Error 1
ERROR: compilation failed for package ‘httpgd’
removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/httpgd’

**Comment by nx10** [comment]
I found this thread about a similar issue: https://stackoverflow.com/questions/58628377/catalina-c-using-cmath-headers-yield-error-no-member-named-signbit-in-th

Your Xcode installation might be corrupted, try updating or reinstalling it.
