### ISSUE TITLE
Plot history gallery view

### ISSUE THREAD

**Issue by nx10** [nx10/httpgd#36]
Add a thumbnail gallery view to the client for visually navigating the plot history.
Maybe implement searching/filtering.

**Comment by nx10** [comment]
Preview:

![Evqj1CwhjR](https://user-images.githubusercontent.com/33600480/105552869-d5041900-5d04-11eb-8f61-f30a8c01ae48.gif)

**Comment by nx10** [comment]
After a couple of iterations this evolved in a general redesign of the client UI. Still needs a lot of testing and polish, but here is a sneak peek of what I have so far:

![](https://i.imgur.com/z9xVMpt.gif)

**Comment by renkun-ken** [comment]
Woow looks so cool, can't wait to use it 🚀

**Comment by nx10** [comment]
I just pushed the updated client. A lot has changed so let me know if you find any bugs.

**Comment by renkun-ken** [comment]
I already installed the latest commit. Looks quite smooth so far. I'll let you know if I find any bugs.

**Comment by renkun-ken** [comment]
The menu and shortcut keys look great! However, it might be dangerous that the user might mistakenly believe that the focus is in the editor and press "T" and all plots are gone. Maybe such command should get a more complex shortcut or none at all?

**Comment by nx10** [comment]
You are right, that is a good suggestion. I will have a look at what keybindings are reserved by browsers and change it to something that is less likely accidentially pressed.

**Comment by nx10** [comment]
> it might be dangerous that the user might mistakenly believe that the focus is in the editor and press "T" and all plots are gone. Maybe such command should get a more complex shortcut or none at all?

"Clear all" is now bound to <kbd>alt</kbd>+<kbd>D</kbd>, this should prevent accidental presses and make it easier to remember as "delete current" is <kbd>D</kbd>.
