### ISSUE TITLE
Font colour won't change

### ISSUE THREAD

**Issue by albersonmiranda** [nx10/httpgd#43]
Hi there!

Text colour don't seem to change:

![bug](https://user-images.githubusercontent.com/45690517/100404172-7ccfd400-303f-11eb-93c9-ae13b222c12f.png)

Other elements like axis ticks, axis lines and annotation arrows (geom_curve) works just fine.

EDIT: (reprex code)

```
plot(mpg ~ cyl, data = mtcars,
       col.lab = "red", col = "blue",
       main = "I won't change colors", col.main = "green")
```

**Comment by renkun-ken** [comment]
Thanks for reporting!

It would be nice if you could put your example code here so that we could easily reproduce it.

**Comment by nx10** [comment]
Thanks for reporting this! Should be fixed now.
