### ISSUE TITLE
Use snake case for function names

### ISSUE THREAD

**Issue by nx10** [nx10/httpgd#44]
The Tidyverse style guide [recommends snake case for function names](https://style.tidyverse.org/syntax.html).
I propose these function name changes:

| old | new |
|-----|-----|
| `httpgdBrowse` | `httpgd_browse` |
| `httpgdClear` | `httpgd_clear` |
| `httpgdCloseAllServers` | `httpgd_close(all = T)` |
| `httpgdCloseServer` | `httpgd_close` |
| `httpgdGenerateToken` | `httpgd_generate_token` |
| `httpgdRemove` | `httpgd_remove` |
| `httpgdSVG` | `httpgd_svg` |
| `httpgdState` | `httpgd_state` |
| `httpgdURL` | `httpgd_url` |

This breaking change should probably be done as soon as possible (before we release to CRAN).

As `httpgd_` is pretty long we could also consider to use `hgd_` instead as a shorter prefix.

**Comment by renkun-ken** [comment]
Since this package is mostly used interactively, breaking changes should not impact as much as those used in any production systems. I agree that these breaking changes should be made as early as possible.

**Comment by nx10** [comment]
The function names are now changed.
