### ISSUE TITLE
HGD bg option

### ISSUE THREAD

**Issue by ElianHugh** [nx10/httpgd#45]
Hi there,

I've been trying to use the bg option for hgd(), but it doesn't seem to be affecting the colour of the viewer from what I can tell. 

E.g.
 `httpgd::hgd(bg = "blue", silent = TRUE)`
`.vsc.browser(httpgd::hgd_url(), "R Plots", viewer = "Beside")`

^ here, the viewer still uses a white background

Am I using this correctly? Thanks!

**Comment by renkun-ken** [comment]
In a vanilla R, `httpgd::hgd(bg = "blue")` does not seem to respect `bg="blue"` at all.

**Comment by nx10** [comment]
Thank you for reporting this bug. Should be fixed now.

Seems like this broke a while ago, I have started working on the graphical unit tests (#41) to prevent something like this in the future.
