### ISSUE TITLE
Font handling is strange?

### ISSUE THREAD

**Issue by psobolewskiPhD** [nx10/httpgd#51]
I originally reported this as an issue with the {sftheme}
https://github.com/amirmasoudabdol/sfthemes/issues/3
This is occurring with 
When using this theme that uses the Inter family of fonts, everything works well, except for a strange issue where ggplot legend title doesn't respect the font settings.
The wrong face is used for the bold legend title in VS Code WebView or in Chrome, as well as when saved to png. (Incidentally, in Mac OS Safari I don't get any of the text elements in Inter...)
![plot](https://user-images.githubusercontent.com/76622105/106392282-62282b80-63f1-11eb-8656-0a79784e291a.png)
Here's the output from ggsave():
![test](https://user-images.githubusercontent.com/76622105/106392297-70764780-63f1-11eb-8d42-b6b19a1783a3.png)

I have the whole Inter family installed, MacOS Big Sur, M1, using {systemfonts} and {extrafont} if that helps.

**Comment by nx10** [comment]
Thank you for reporting, I will look into it.

**Comment by nx10** [comment]
I just updated the font handling can you try the newest development version from github?

Plots do look a bit broken for me with that package on any graphics device, regardless of fonts:

![image](https://user-images.githubusercontent.com/33600480/106662356-91ca6580-65a2-11eb-8025-ef16446eedb9.png)

(This is with the R studio GD)

**Comment by psobolewskiPhD** [comment]
On my end, the test plot
```
ggplot(mtcars) +
   geom_point(aes(x = wt, y = mpg, colour = factor(gear))) +
   labs(title = "Fuel Economy",
        subtitle = "Fuel economy declines as weight increases, 1973-74",
        caption = "Data from the 1974 Motor Trend US magazine.",
        x = "Weight (1000 lbs)",
        y = "MPG",
        colour = "Gears") +
   facet_grid(vs ~ am) +
   sf_set_inter(theme_linedraw()) +
   scale_colour_ios_light()
```

looks correct in VS Code (and Chrome)
![plot](https://user-images.githubusercontent.com/76622105/106663285-ca1e7380-65a3-11eb-98f4-c229bb360db3.png)
This is with the save to PNG in httpgd. Resolution lower than ggsave() but the font handling appears correct and the behavior is proper with (+)/zoom.

BTW in Safari now the fonts are even more interesting:
![plot-2](https://user-images.githubusercontent.com/76622105/106663595-37ca9f80-65a4-11eb-948f-54796dfde19d.png)
The font is not respected anywhere but the Legend title?

**Comment by nx10** [comment]
Can you attach the SVG file?

**Comment by psobolewskiPhD** [comment]
Here's the dark theme with bumping the font size up:
PNG from VS Code (using the icon in httpgd)
![plot](https://user-images.githubusercontent.com/76622105/106664619-99d7d480-65a5-11eb-9f4f-c2951ee9fa7e.png)
SVG from safari (zipped, apparently not supported by GitHub)
[plot-2.svg.zip](https://github.com/nx10/httpgd/files/5914559/plot-2.svg.zip)

PNG from Safari (using the icon in httpgd)
![plot-3](https://user-images.githubusercontent.com/76622105/106664828-e15e6080-65a5-11eb-8ed1-7c3f16210851.png)

**Comment by nx10** [comment]
It seems like Safari can not find the "Inter" font on your computer. Have you tried restarting your computer?
You can also embed it into the SVGs if you start httpgd with:

```R
hgd(extra_css = "@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');")
```

**Comment by psobolewskiPhD** [comment]
So doing:
`httpgd::hgd(extra_css = "@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');")                                                  `
gives me a blank screen in VS Code and Safari and Chrome...
I'm pretty sure I've restarted numerous times since installing Inter, but probably not since installing the sfthemes and httpgd? Can't be sure..

**Comment by psobolewskiPhD** [comment]
I'm going to restart VS Code et al. and see what that does. (sometimes I still get the blank canvas in httpgd randomly).

**Comment by nx10** [comment]
If you have used the script of Kun Ren for using httpgd in vscode, make sure to add the extra_css argument to the hgd(..., extra_css = ...) call in your .Rprofile

The blank screen issue is most likely this https://github.com/nx10/httpgd/issues/50 bug in R itself which will be fixed in the upcoming R version.

**Comment by nx10** [comment]
The extra_css argument will just include an URL for Inter as a source in all plots, in case that font is used but not available.

**Comment by psobolewskiPhD** [comment]
Thanks for the info.
Honestly, I never use Safari for this stuff, just VS Code and the issues seem resolved there.
I rather control the font in the theme/ggplot call and not at the .Rprofile level, so I think the current behavior is fine.
Now I'm getting broken PDFs generated via ggsave() with this {sftheme} so something else seems to be an issue...

**Comment by nx10** [comment]
Thank you for for your reports, yes it does seem like sftheme is a bit unstable at the moment.
Glad it works as expected in vscode now!

**Comment by psobolewskiPhD** [comment]
No no, thank you for httpgd which is legit awesome and for being patient with me and my crappy issues!
