### ISSUE TITLE
Control whether to show history by default

### ISSUE THREAD

**Issue by renkun-ken** [nx10/httpgd#60]
The history view look amazing. I wonder if there's a way to control whether to show it by default?

**Comment by nx10** [comment]
You can now pass the `history=F` parameter to both `hgd_browse` and `hgd_url` to control the default sidebar visibility b48300ca188967ca7b6675b4c790ca806d0e49f3

As a small patch release is needed for CRAN this is also included in the upcoming 1.1.1 release.
