### ISSUE TITLE
save as png?

### ISSUE THREAD

**Issue by r2evans** [nx10/httpgd#9]
I know it's not necessarily an easy thing, have you considered adding a "save as png" option? I know I can do a screenshot, but that suggests either imperfect borders (e.g., in windows, `ctrl-shift-s` screen snip, drag across the rectangle of screen to save); or including browser tabs/components in the image (printscreen, either full or just single-app `alt-prtscrn`), which often requires post-shot editing.

Suggested options:

1. In R, just open a `png()`, replay the plot, and save and export to the browser. (I expect this would be on-demand, but in a pinch you could always produce both svg and png for quick export.)
2. In javascript, where a hasty search presents some approaches: https://www.npmjs.com/package/save-svg-as-png and https://stackoverflow.com/q/3975499 (several, though most out-dated).

Thanks again!

**Comment by nx10** [comment]
Thank you for your suggestion. 
I designed the server in a way that will allow rendering to different formats. PNG and other raster graphics will be possible as I already depend on cairo to calculate don't metrics ahead of time. 
But the the focus for the project right now is on reliability and stability as well as making embedding in editors (vscode, atom, ...) possible.

After that "save as PNG" is definitely something I want to implement. "Copy to clipboard" to quickly paste plots anywhere would be interesting as well.

**Comment by nx10** [comment]
The client is now able to save PNG plots. You can try it by pressing ctrl+R

**Comment by r2evans** [comment]
I appreciate adding the feature, thank you!

Do you think it wise to override a standard shortcut for browsers? I think `Ctrl+R` is fairly common for reloading the page.

**Comment by nx10** [comment]
You are right, do you have a suggestion for a different shortcut?

**Comment by r2evans** [comment]
Thoughts:

- add another button next to the download button

    ![image](https://user-images.githubusercontent.com/5815808/93226785-8deb9300-f728-11ea-954e-41ce0d4fdfbd.png)

- if you can arbitrarily assign keyboard shortcuts, is there a reason you need to use `Ctrl`? I know some *websites* allow non-modified keyboard shortcuts, but that's not a browser-based thing.  When I open `httpgd::httpgd()` in FF or Edge, these are the only unmodified keys that evoke any effect for me:

    - FF 80.0.1: `/` (quick find); `'` (quick find, links only)
    - Edge 85.0.564.51: `-` and `_` (decrease httpgd zoom); `=` and `+` (increase httpgd zoom)

    With that, perhaps: save as `S`vg; save as `P`ng; `D`elete? (It would be useful to have these as tooltips over the buttons too, for easy just-in-time learning.)

**Comment by nx10** [comment]
Great suggestions as always. I will implement it like that soon.

**Comment by nx10** [comment]
I implemented the changes a while ago, a full list of all available shortcuts can be found in the readme. Plot scaling is not yet working in the browser rendered PNGs (I opened a new issue for that https://github.com/nx10/httpgd/issues/35).
