### ISSUE TITLE
httpgd package can not be installed

### ISSUE THREAD

**Issue by seedvestige** [nx10/httpgd#98]
I tried to install httpgd package in R, but it showed error as below during installation.

C++17 standard requested but CXX17 is not defined

R was installed in Centos7, R version is 4.1.2

Thank you so much for your help!

**Comment by nx10** [comment]
Thank for checking out httpgd.

It seems like you have to update your C++ compiler. 

I never used CentOS myself so I am not sure how this is done there.

Let me know if this helps.

**Comment by nx10** [comment]
If you have a modern compiler installed you may have to point R towards it in the `~/.R/Makevars` by adding something like:

```
CXX17 = g++-7 -std=gnu++17 -fPIC
```

https://travis-ci.community/t/error-in-shlib-internal-args-c-17-standard-requested-but-cxx17-is-not-defined/6748/4

**Comment by seedvestige** [comment]
Thank you so much, I have solved this problem by installing the new version GCC.
